### PR TITLE
Simple bug fixes

### LINKED ISSUE #315: TileStorage checked_remove does not actually check.
Like the title says. This should be a quick fix.

Issue in code:
https://github.com/StarArawn/bevy_ecs_tilemap/blob/de8d005331dde7d9ebb8c4fe1b36769b84e44be5/src/tiles/storage.rs#L84

### PR DESCRIPTION
**Pull request by bzm3r**
Fixes #315 and #314

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -54,8 +54,12 @@ impl Plugin for TilemapPlugin {
         #[cfg(not(feature = "atlas"))]
```
Comment (bzm3r) [inline src/lib.rs:54]: Should I just make this `#[cfg(all(not(feature = "atlas"), feature = "render"))]`?

Comment (StarArawn) [reply src/lib.rs:54]: Yes

**Review by StarArawn — CHANGES_REQUESTED** [review]

**Review by StarArawn — APPROVED** [review]
